### ISSUE TITLE
epsie src tarball doesn't carry LICENSE file

### ISSUE THREAD

**Issue by duncanmmacleod** [cdcapano/epsie#14]
The src tarball for epsie-0.4.1 on PyPI doesn't include the LICENSE file, can this be added for future releases (this is a condition of GPL)?

**Comment by cdcapano** [comment]
@duncanmmacleod Thanks for pointing that out; I'll fix it in the next release.

**Comment by cdcapano** [comment]
@duncanmmacleod I've just uploaded version 0.5 to pypi, and made sure the license was included.
